
.PHONY: package
package:
	tar --exclude='data-raw' --exclude='.DS_Store' --exclude='Makefile' \
	--exclude='part-dashboard.tar.gz' --exclude='README.md' \
	--exclude='setup.R' \
	-zcvf part-dashboard.tar.gz .


